=encoding utf8

=head1 VkPlayListDownloader

Perl script for downloading user playlist to hard disk


=head2 Install dependence

	cpanm  --installdeps .

=head2 Edit config

	{
		"user": {
			"login": "YouLogin",
			"password": "You Password"
		},
		"path": {
			"saveTo": "./saved" // save mp3 to dir
		}
	}

=head2 Download music

	./parser.pl --user patr14ek
