=encoding utf8

=head1 VkPlayListDownloader

Perl script for downloading user playlist to hard disk


=head2 Install dependence

	cpanm  --installdeps .

=head2 Edit config

	{
		"user": {
			"login": "YouLogin",
			"password": "You Password"
		},
		"path": {
			"saveTo": "./saved" // save mp3 to dir
		}
	}

=head2 Download music

	./parser.pl --user patr14ek

=head2 Help message

	# VK.com playlist downloader v0.1
	# Author: SHok
	
	Set user:
	--user [ patr14ek | id123 ]
	
	Output debug level:
	--debug [ <info> | detail | debug ]
	
	Sort tracks by artist:
	-sba
	
	Sort by playlists:
	-sbp
